GET http://localhost:3000

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "LeDucPhanAnh@gmail.com",
    "password": "abc123"
}

###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGRmMTk2YzdmZWFkZjIxMzAwZmZiNjgiLCJpYXQiOjE2OTI2MDE3NDEsImV4cCI6MTcyNDE1OTM0MX0.xkBlvOlS0aySnBCWbkYq_2UPKZ1sCC5sdI0Gdyip6wM"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "LeDucPhanAnh@gmail.com",
    "password": "abc123"
}

###
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGRmMTk2YzdmZWFkZjIxMzAwZmZiNjgiLCJpYXQiOjE2OTI2MDI4MjQsImV4cCI6MTcyNDE2MDQyNH0.K4NAfLUGi-Oh18ZpEYkAEc4EOD-14_zAfc9Im4vz0Co"
}

###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGRmMTk2YzdmZWFkZjIxMzAwZmZiNjgiLCJpYXQiOjE2OTI2MDA4MzksImV4cCI6MTY5MjYwMDg5OX0.kax1qeFfKTdtZWNfLISZJCxUZDnZFsoa6azLK-NGhLQ
